name: hexlet-ci-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: say hello
        run: make say-hello
      - name: do setup
        run: make setup
      - name: do start
        run: make start
      - name: do test
        run: make test
      - name: do checkstyle
        run: make lint
